image: codeception/codeceptjs:latest

stages:
  - chrome-ci

variables:
  TEST_TAG: test
  SCREEN_WIDTH: 1920
  SCREEN_HEIGHT: 1080

services:
  - name: selenium/standalone-chrome:latest

e2e-tests-chrome:
  stage: chrome-ci

  before_script:
    - apt -y update
    - apt -y install default-jre
    - chmod 777 test_runner.sh
    - npm run build
  script:
    - ./test_runner.sh prod $TEST_TAG true
  after_script:
    - cp -r output/ ci_artifacts/
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
     - ci_artifacts/
    when: always
